[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.9.0"

[[constraint]]
  name = "github.com/HdrHistogram/hdrhistogram-go"
  version = "0.9.0"

[[constraint]]
  name = "github.com/uber-go/tally"
  version = ">=2.1.0, <4.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true
