name: "Unit Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        job:
        - dep: true
          glide: false
          name: unit-tests with dep
        - dep: false
          glide: true
          name: unit-tests with glide
    name: ${{ matrix.job.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Setup GOPATH
        uses: ./.github/actions/setup-gopath
      - name: Install dependencies and tools
        run: |
          cd $PROJECT
          make install-ci USE_DEP=${{ matrix.job.dep }} USE_GLIDE=${{ matrix.job.glide }}
      - name: Run tests
        run: |
          cd $PROJECT
          make test-ci USE_DEP=${{ matrix.job.dep }} USE_GLIDE=${{ matrix.job.glide }}
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          file: cover.out
          fail_ci_if_error: true
          verbose: true
